### ISSUE TITLE
Firmware license

### ISSUE THREAD

**Issue by TechnologyClassroom** [wizarddata/Ergo-S-1#1]
The README states, "The hardware is released under CERN OHL-S v2. Full license text is available in the SOURCE folder."  What is the license for everything else including the firmware?

**Comment by wizarddata** [comment]
The firmware is from the ZMK project, which is released under MIT. I think the documentation falls under the same license as the hardware, so I could change the wording to 'hardware and associated documentation'.

**Comment by wizarddata** [comment]
Change was implemented.
