### ISSUE TITLE
Keymap json

### ISSUE THREAD

**Issue by hasrthur** [wizarddata/Ergo-S-1#3]
Hi! 
First of all thank you very much for making this keyboard!

I am trying to setup a layout for myself and would like to use https://nickcoutsos.github.io/keymap-editor/ but it requires a json file with key positions.

Do you happen to have one? And if yes, could you please provide one?

Thank you in advance!

**Comment by wizarddata** [comment]
I haven't made one, but if you ask in the discord I'm pretty sure someone else has.

**Comment by arcanemachine** [comment]
@hasrthur I made a couple repos that simplify the process of customizing and building the firmware for your desired layout:

https://github.com/arcanemachine/ergo-s-1-zmk-config - Fork this and import it to the Keymap Editor application (the application has instructions on how to do this.)

https://github.com/arcanemachine/zmk-ergo-s-1 - This contains a fork of ZMK with the required files to build the firmware for the Ergo S-1, and also has some changes that fix issues with newer versions of the OS that runs the keyboard (Zephyr).
